--1.1
SELECT *
FROM TEILESTAMM t 

--1.2
SELECT *
FROM TEILESTAMM t 
WHERE UPPER(t.BEZEICHNUNG) LIKE '%CITY%'

--1.3
SELECT a.TEILNR, SUM(GESAMTPREIS) umsatz
FROM AUFTRAGSPOSTEN a
GROUP BY a.TEILNR
ORDER BY umsatz DESC
--HAVING SUM(a.GESAMTPREIS) = (SELECT MAX(SUM(a2.GESAMTPREIS)) FROM AUFTRAGSPOSTEN a2 GROUP BY a2.TEILNR) 

--1.4
SELECT COUNT(*)
FROM KUNDE k

SELECT COUNT(*)
FROM PERSONAL p 

SELECT COUNT(*)
FROM TEILESTAMM t 

--1.5
SELECT MIN(DATUM) AS von, MAX(DATUM) AS bis
FROM AUFTRAG a 

--1.6
SELECT k.NAME AS Kunde, p.NAME AS Personal 
FROM KUNDE k, AUFTRAG a, PERSONAL p
WHERE a.AUFTRNR = 2 AND k.NR = a.KUNDNR AND p.PERSNR = a.PERSNR 

SELECT NAME AS Vorgesetzte
FROM PERSONAL p 
WHERE PERSNR = 1

--1.7
SELECT *
FROM LAGER l 
WHERE BESTAND > 0
ORDER BY BESTAND

--1.8
SELECT DISTINCT TEILNR 
FROM LIEFERUNG l 
ORDER BY TEILNR DESC 

--1.9
SELECT TEILNR AS Teilenummer, BEZEICHNUNG AS Bezeichnung, PREIS AS Bruttopreis
FROM TEILESTAMM t 
WHERE PREIS > 30

--1.10
SELECT EINZELTEILNR AS Teilenummer
FROM TEILESTRUKTUR t 
WHERE OBERTEILNR = 300001 AND ANZAHL > 100



